import { education } from '../data/content';

const EducationWindow = () => {
  return (
    <div className="h-full overflow-y-auto p-4 text-[11px] leading-5 text-slate-900">
      <header className="mb-4">
        <h2 className="text-sm font-semibold">Education</h2>
        <p className="text-[11px] text-slate-500">
          Academic milestones and educational achievements.
        </p>
      </header>

      <ol className="relative ml-3 border-l border-slate-200 pl-5">
        {education.map((entry) => (
          <li key={entry.title} className="mb-6 last:mb-0">
            <span className="absolute -left-2.5 mt-1 h-2 w-2 rounded-full border border-white bg-aqua-500" />
            <div className="flex flex-col gap-1.5">
              <div>
                <h3 className="text-xs font-semibold text-slate-900">
                  {entry.title}
                </h3>
                <p className="text-[11px] uppercase tracking-wide text-slate-400">
                  {entry.period}
                </p>
              </div>
              <p className="text-[11px] leading-relaxed text-slate-600">
                {entry.dissertationLink ? (
                  <>
                    Final Dissertation:{' '}
                    <a
                      href={entry.dissertationLink}
                      target="_blank"
                      rel="noreferrer"
                      className="text-blue-600 hover:underline"
                    >
                      "Using data generated by a GAN to improve the accuracy of a CNN image classification model in the case of a small amount of initial data"
                    </a>
                    . Relevant Courses: Image and Text Analysis with Deep Learning, Time Series Analysis for Finance, Machine Learning, Cloud Technologies and Big Data Frameworks, Data Warehousing.
                  </>
                ) : (
                  entry.summary
                )}
              </p>
            </div>
          </li>
        ))}
      </ol>
    </div>
  );
};

export default EducationWindow;

