export const profile = {
  name: 'Nicolò Tognoni',
  title: 'Packaged App Development Senior Analyst',
  location: 'Milan, Italy',
  mission:
    'Backend developer and GenAI innovator leading feature development for enterprise order management platforms. Specializing in Java, Spring Boot, and GenAI agent systems for automated code review and development efficiency.',
  highlights: [
    'Leading cross-functional teams and feature development at Accenture Industry X',
    'Designed and integrated GenAI agent systems for automated PR code review',
    'International Master in Business Analytics and Big Data from POLIMI Graduate School of Management'
  ],
};

export const timeline = [
  {
    title: 'Packaged App Development Senior Analyst — Accenture Industry X',
    period: 'Nov 2024 – Present',
    summary:
      'Leading specific features and functionalities of the backend order management platform, managing cross-functional teams across Italy and India. Independently designed and integrated GenAI agent systems for automated code review of pull requests, significantly accelerating the PR review workflow.',
  },
  {
    title: 'Packaged App Development Analyst — Accenture Industry X',
    period: 'Oct 2023 – Oct 2024',
    summary:
      'Developed backend systems using Java, Spring Boot, and Hibernate for order management platform, managing SQL databases and API development.',
  },
  {
    title: 'Backend Development Intern — Accenture Industry X',
    period: 'Jan 2023 – Sep 2023',
    summary:
      'Contributed to backend development and Python computer vision projects, managing data collection and labeling processes to improve model training accuracy.',
  },
  {
    title:
      'International Master in Business Analytics and Big Data — POLIMI Graduate School of Management',
    period: 'Sep 2021 – Sep 2022',
    summary:
      'Final Dissertation: "Using data generated by a GAN to improve the accuracy of a CNN image classification model in the case of a small amount of initial data". Focused on image and text analysis with deep learning, time-series analytics for finance, cloud technologies, and data warehousing.',
  },
  {
    title: "Bachelor's Degree in Business Administration and Management — Bocconi University",
    period: 'Sep 2016 – Apr 2020',
    summary:
      'Final Dissertation: "Amazon\'s Supply Chain". Covered statistics, Python programming, applied mathematics, financial markets, management, business strategy, relational databases, and SQL.',
  },
  {
    title: 'High School Diploma in Scientific Studies — Liceo Scientifico A. Righi, Cesena',
    period: 'Sep 2011 – Jul 2016',
    summary:
      'STEM-focused curriculum with an exchange program at Carmel High School, California (Jan 2015 – Jun 2015).',
  },
];

export const education = [
  {
    title:
      'International Master in Business Analytics and Big Data — POLIMI Graduate School of Management',
    period: 'Sep 2021 – Sep 2022',
    summary:
      'Final Dissertation: "Using data generated by a GAN to improve the accuracy of a CNN image classification model in the case of a small amount of initial data". Relevant Courses: Image and Text Analysis with Deep Learning, Time Series Analysis for Finance, Machine Learning, Cloud Technologies and Big Data Frameworks, Data Warehousing.',
    dissertationLink: 'https://github.com/nicolotognoni/GAN_for_increasing_CNN_accuracy',
  },
  {
    title: "Bachelor's Degree in Business Administration and Management — Bocconi University",
    period: 'Sep 2016 – Apr 2020',
    summary:
      'Final Dissertation: "Amazon\'s Supply Chain". Relevant Courses: Computer Science (Python), Statistics, Applied Mathematics, Mathematics, Financial Markets, Management, Business Strategy, Relational Databases, SQL.',
  },
  {
    title: 'High School Diploma in Scientific Studies — Liceo Scientifico A. Righi, Cesena',
    period: 'Sep 2011 – Jul 2016',
    summary:
      'STEM-focused curriculum with an exchange program at Carmel High School, California (Jan 2015 – Jun 2015).',
  },
];

export const workExperience = [
  {
    title: 'Packaged App Development Senior Analyst — Accenture Industry X',
    period: 'Nov 2024 – Present',
    summary:
      'Leading specific features and functionalities of the backend order management platform, managing cross-functional teams across Italy and India. Independently designed and integrated GenAI agent systems for automated code review of pull requests, significantly accelerating the PR review workflow. Taking full responsibility for code quality and delivery timelines while mentoring junior developers and coordinating with offshore teams.',
  },
  {
    title: 'Packaged App Development Analyst — Accenture Industry X',
    period: 'Oct 2023 – Oct 2024',
    summary:
      'Developed backend systems using Java, Spring Boot, and Hibernate for order management platform, managing SQL databases and API development.',
  },
  {
    title: 'Backend Development Intern — Accenture Industry X',
    period: 'Jan 2023 – Sep 2023',
    summary:
      'Contributed to backend development and Python computer vision projects, managing data collection and labeling processes to improve model training accuracy.',
  },
];

export const projects = [
  {
    name: 'Recapy - Swift iOS App',
    year: 2025,
    description:
      'iOS app that transforms lengthy YouTube videos into concise, structured summaries powered by ChatGPT. Features comprehensive summaries with key points, full transcripts with timestamps, highlighted quotes, and one-click sharing. Built with a freemium model offering one daily summary for free users, with premium subscriptions for unlimited access. Perfect for students, professionals, and lifelong learners who want to maximize knowledge acquisition.',
    stack: ['Swift', 'Xcode', 'iOS', 'ChatGPT API', 'Cursor AI'],
    link: 'https://apps.apple.com/it/app/recapy-ai-youtube-summary/id6742327277',
    image: '/src/components/ui/icons/appIcon.png',
  },
  {
    name: 'GAN for Increasing CNN Accuracy',
    year: 2021,
    description:
      'Master thesis project exploring the use of GAN-generated data to improve CNN image classification accuracy with limited initial datasets. Implemented StyleGAN2-ADA training and evaluated the minimum dataset size threshold for effective synthetic data augmentation.',
    stack: ['Python', 'StyleGAN2-ADA', 'CNN', 'TensorFlow', 'Google Colab'],
    link: 'https://github.com/nicolotognoni/GAN_for_increasing_CNN_accuracy',
    image: '/src/components/ui/images/cifar-10.png',
  },
  {
    name: 'Satellite Image Classification CNN',
    year: 2021,
    description:
      'Convolutional Neural Network for classifying satellite images into 21 land-use categories using the UC Merced dataset. Achieved 82% accuracy with custom CNN architecture and 93% accuracy using Transfer Learning with InceptionV3 pre-trained on ImageNet.',
    stack: ['Python', 'TensorFlow', 'CNN', 'Transfer Learning', 'InceptionV3'],
    link: 'https://github.com/nicolotognoni/Satellite_Image_Classification_CNN',
    image: '/src/components/ui/images/bgr2-2.jpg',
  },
];

export const skillGroups = [
  {
    label: 'Programming',
    items: ['Java', 'Python', 'SQL', 'R', 'Swift', 'C/C++'],
  },
  {
    label: 'Frameworks & Tools',
    items: ['Spring Boot', 'Hibernate', 'Machine Learning', 'Computer Vision', 'Generative AI', 'Agents', 'LangChain', 'LangGraph'],
  },
  {
    label: 'Languages',
    items: ['Italian (Native)', 'English (C1 IELTS)'],
  },
];

export const contactChannels = [
  {
    label: 'Email',
    value: 'nicolo.tognoni1@gmail.com',
    href: 'mailto:nicolo.tognoni1@gmail.com',
  },
  {
    label: 'LinkedIn',
    value: 'linkedin.com/in/nicolotognoni',
    href: 'https://www.linkedin.com/in/nicolotognoni/',
  },
  {
    label: 'GitHub',
    value: 'github.com/nicolotognoni',
    href: 'https://github.com/nicolotognoni',
  },
];

export const resumeLink = '/nicolotognoni_resume.pdf';

export const articles = [
  {
    name: 'Building Feedforward Neural Networks from Scratch',
    year: 2022,
    datePublished: 'Oct 1, 2022',
    description:
      'Comprehensive guide to understanding Feed Forward Neural Networks (FFNNs) from the basics. Covers Perceptrons, Deep Neural Networks, Gradient Descent, and Backpropagation. Includes a hands-on tutorial building an FFNN in Python using TensorFlow with the MNIST dataset, achieving 99% accuracy.',
    stack: ['Python', 'TensorFlow', 'Neural Networks', 'Deep Learning', 'MNIST'],
    link: 'https://medium.com/towards-artificial-intelligence/building-feedforward-neural-networks-from-scratch-c5a5cf23b97b',
    image: '/src/components/ui/images/articles_cover/1*1HbdwyCE8coZLetO40qdXA.webp',
  },
  {
    name: 'Building iOS Applications - Comprehensive Technical Analysis',
    year: 2025,
    datePublished: 'Jul 4, 2025',
    description:
      'A comprehensive technical analysis of modern iOS development architectures, covering SwiftUI, UIKit, MVVM patterns, and best practices for building scalable iOS applications. Explores the evolution of iOS development frameworks and provides insights into modern app architecture design.',
    stack: ['Swift', 'iOS', 'SwiftUI', 'UIKit', 'MVVM'],
    link: 'https://medium.com/@nicolotognoni/building-ios-applications-a-comprehensive-technical-analysis-of-modern-development-architectures-1f3b33981f7b',
    image: '/src/components/ui/images/articles_cover/1*Yc6XguAzVdVLphHJXRfprA.webp',
  },
  {
    name: 'Creating a Virtual Environment with WSL2 and Linux on Windows 11',
    year: 2023,
    datePublished: 'Mar 14, 2023',
    description:
      'Step-by-step guide to installing Windows Subsystem for Linux (WSL2) and Ubuntu on Windows 11, then creating a Python virtual environment. Covers both command-line and Microsoft Store installation methods, configuration, and best practices for cross-platform development.',
    stack: ['WSL2', 'Linux', 'Ubuntu', 'Python', 'Windows'],
    link: 'https://medium.com/geekculture/creating-a-virtual-environment-with-wsl2-and-linux-on-windows-11-5ffa027ad87a',
    image: '/src/components/ui/images/articles_cover/1*rGElibzwzjvaO_5I60xg9g.webp',
  },
  {
    name: 'Train StyleGAN2-ADA with Custom Datasets in Colab',
    year: 2022,
    datePublished: 'Sep 14, 2022',
    description:
      'Complete tutorial on training NVIDIA\'s StyleGAN2-ADA on custom datasets in Google Colab using TensorFlow 1.14. Covers data preparation, fine-tuning techniques, and result analysis. Perfect for anyone looking to generate high-quality synthetic images using state-of-the-art GAN technology.',
    stack: ['Python', 'StyleGAN2-ADA', 'TensorFlow', 'Google Colab', 'GANs'],
    link: 'https://medium.com/geekculture/train-stylegan2-ada-with-custom-datasets-in-colab-11accf22ef9b',
    image: '/src/components/ui/images/articles_cover/1*S1SozupIv-22cpP2qECnfQ.webp',
  },
];

